name: Run Cypress Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress Tests
        id: run_cypress
        run: |
          set +e
          npx cypress run || exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_ENV
          set -e

      - name: Handle Test Results
        if: env.exit_code != '0'
        run: |
          echo "Cypress tests failed. Reverting to previous version..."
          git config --global user.email "20210658@uthh.edu.mx"
          git config --global user.name "rodrigo3829l"
          git reset --hard HEAD^
          git push https://github.com/rodrigo3829l/page_user_mygardenllc.git --force
