name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        id: run_tests
        run: |
          # Ejecuta las pruebas unitarias
          yarn test:unit || exit_code=$?
          # Guarda el código de salida en el entorno de GitHub Actions
          echo "exit_code=$exit_code" >> $GITHUB_ENV

      - name: Handle test results
        if: env.exit_code != '0'
        run: |
          echo "Tests failed. Reverting to previous version..."
          # Configura la identidad de Git para revertir el commit
          git config --global user.email "20210658@uthh.edu.mx"
          git config --global user.name "rodrigo3829l"
          # Revertimos el commit fallido
          git reset --hard HEAD^
          # Forzamos el push para actualizar el estado remoto del repositorio
          git push https://x-access-token:${{ secrets.MY_GH_TOKEN }}@github.com/rodrigo3829l/db_api_mygarden_llc.git --force
